-- Generated by TinyC# transpiler
b2 = {}
b2.__index = b2

function b2.new()
  local self = setmetatable({}, b2)
  self.STATIC = 0
  self.KINEMATIC = 1
  self.DYNAMIC = 2
  return self
end

function b2.createWorld(gx, gy)
  return nil
end

function b2.destroyWorld(w)
end

function b2.createBody(w, type, x, y)
  return nil
end

function b2.addBox(body, hw, hh, density, friction, restitution)
end

function b2.worldStep(w, dt, substeps)
end

function b2.getPositionX(body)
  return 0
end

function b2.getPositionY(body)
  return 0
end

Body = {}
Body.__index = Body

function Body.new(label, handle)
  local self = setmetatable({}, Body)
  self.Label = label
  self.Handle = handle
  return self
end

Simulation = {}
Simulation.__index = Simulation

function Simulation.new()
  local self = setmetatable({}, Simulation)
  self.Bodies = {}
  self.Log = {}
  return self
end

function Simulation:Init()
  self.World = b2.createWorld(0, -10)
  local ground = b2.createBody(self.World, b2.STATIC, 0, -1)
  b2.addBox(ground, 50, 1, 0, 0.3, 0)
  local box1 = b2.createBody(self.World, b2.DYNAMIC, 0, 10)
  b2.addBox(box1, 0.5, 0.5, 1, 0.3, 0.2)
  table.insert(self.Bodies, Body.new("BoxA", box1))
  local box2 = b2.createBody(self.World, b2.DYNAMIC, 0.8, 20)
  b2.addBox(box2, 0.5, 0.5, 1, 0.3, 0.5)
  table.insert(self.Bodies, Body.new("BoxB", box2))
  local box3 = b2.createBody(self.World, b2.DYNAMIC, -0.3, 30)
  b2.addBox(box3, 0.5, 0.5, 1, 0.3, 0.8)
  table.insert(self.Bodies, Body.new("BoxC", box3))
end

function Simulation:Snapshot()
  local line = ""
  for i = 0, #self.Bodies - 1 do
    local body = self.Bodies[i + 1]
    local y = b2.getPositionY(body.Handle)
    if i > 0 then
      line = line .. "  "
    end
    line = line .. body.Label .. ":y=" .. tostring(y)
  end
  return line
end

function Simulation:Step(dt, substeps)
  b2.worldStep(self.World, dt, substeps)
end

function Simulation:Cleanup()
  b2.destroyWorld(self.World)
end

Demo = {}
Demo.__index = Demo

function Demo.new()
  local self = setmetatable({}, Demo)
  return self
end

function Demo.Run()
  local sim = Simulation.new()
  sim:Init()
  table.insert(sim.Log, "=== Box2D v3 + TinyC# Headless Physics ===")
  table.insert(sim.Log, "3 boxes dropping under gravity (0,-10)")
  table.insert(sim.Log, "Simulating 3s at 60Hz...")
  table.insert(sim.Log, "")
  local totalFrames = 180
  local printEvery = 30
  for frame = 1, totalFrames do
    sim:Step(1.0 / 60.0, 4)
    if frame % printEvery == 0 then
      local t = frame / 60.0
      table.insert(sim.Log, "t=" .. tostring(t) .. "s: " .. sim:Snapshot())
    end
  end
  table.insert(sim.Log, "")
  table.insert(sim.Log, "Final: " .. sim:Snapshot())
  sim:Cleanup()
  table.insert(sim.Log, "Done.")
  local result = ""
  for i = 0, #sim.Log - 1 do
    if i > 0 then
      result = result .. "\n"
    end
    result = result .. sim.Log[i + 1]
  end
  return result
end
