namespace TinyCs.Luoc;

internal sealed partial class CEmitter
{
    private const string RuntimePrelude = """
        /* Generated by luoc from TinyC# IL. */
        /* strict f32 flags: -ffp-contract=off -fexcess-precision=standard */
        #include <stdbool.h>
        #include <float.h>
        #include <inttypes.h>
        #include <limits.h>
        #include <stdint.h>
        #include <stdio.h>
        #include <stdlib.h>
        #include <string.h>

        _Static_assert(sizeof(float) == 4, "luoc requires IEEE-754 binary32");
        _Static_assert(FLT_RADIX == 2 && FLT_MANT_DIG == 24,
            "luoc requires IEEE-754 binary32");
        #if FLT_EVAL_METHOD != 0
        #error "luoc strict mode requires FLT_EVAL_METHOD == 0"
        #endif

        typedef struct TcsArray {
            size_t length;
            size_t element_size;
            void *data;
        } TcsArray;

        static uint32_t tcs_digest;

        static _Noreturn void
        tcs_fault(const char *kind)
        {
            fprintf(stderr, "TinyC# fault: %s\n", kind);
            exit(EXIT_FAILURE);
        }

        static void *
        tcs_alloc(size_t size)
        {
            void *allocation = calloc(1, size);
            if (allocation == NULL) tcs_fault("allocation");
            return allocation;
        }

        static void *
        tcs_nonnull(void *object)
        {
            if (object == NULL) tcs_fault("null");
            return object;
        }

        static TcsArray *
        tcs_array_new(int32_t length, size_t element_size)
        {
            TcsArray *array;
            if (length < 0) tcs_fault("negative-array-length");
            if ((size_t)length > SIZE_MAX / element_size)
                tcs_fault("allocation-overflow");
            array = tcs_alloc(sizeof(*array));
            array->length = (size_t)length;
            array->element_size = element_size;
            if (length != 0) array->data = tcs_alloc((size_t)length * element_size);
            return array;
        }

        static void *
        tcs_array_at(TcsArray *array, int32_t index)
        {
            tcs_nonnull(array);
            if (index < 0 || (size_t)index >= array->length)
                tcs_fault("bounds");
            return (unsigned char *)array->data + (size_t)index * array->element_size;
        }

        static int32_t
        tcs_array_length(TcsArray *array)
        {
            tcs_nonnull(array);
            if (array->length > INT32_MAX) tcs_fault("array-length-overflow");
            return (int32_t)array->length;
        }

        static float
        tcs_f32(uint32_t bits)
        {
            float value;
            memcpy(&value, &bits, sizeof(value));
            return value;
        }

        static int32_t
        tcs_idiv(int32_t left, int32_t right)
        {
            if (right == 0) tcs_fault("divide-by-zero");
            if (left == INT32_MIN && right == -1) tcs_fault("divide-overflow");
            return left / right;
        }

        static int32_t
        tcs_irem(int32_t left, int32_t right)
        {
            if (right == 0) tcs_fault("divide-by-zero");
            if (left == INT32_MIN && right == -1) tcs_fault("divide-overflow");
            return left % right;
        }

        static int32_t
        tcs_shl(int32_t value, int32_t count)
        {
            return (int32_t)((uint32_t)value << ((uint32_t)count & UINT32_C(31)));
        }

        static int32_t
        tcs_shr(int32_t value, int32_t count)
        {
            uint32_t shift = (uint32_t)count & UINT32_C(31);
            uint32_t bits = (uint32_t)value;
            if (shift == 0) return value;
            if (value >= 0) return (int32_t)(bits >> shift);
            return (int32_t)((bits >> shift) | (~UINT32_C(0) << (32 - shift)));
        }

        static void
        tcs_digest_float(float value)
        {
            uint32_t bits;
            unsigned int shift;
            memcpy(&bits, &value, sizeof(bits));
            for (shift = 0; shift < 32; shift += 8) {
                tcs_digest ^= (bits >> shift) & UINT32_C(0xff);
                tcs_digest *= UINT32_C(16777619);
            }
        }

        """;
}
