namespace TinyCs.Tcs2c;

internal sealed partial class CEmitter
{
    private const string RuntimePrelude = """
        /* Generated by tcs2c from TinyC# IL. */
        /* strict f32 flags: -ffp-contract=off -fexcess-precision=standard */
        #include <stdbool.h>
        #include <stddef.h>
        #include <math.h>
        #include <float.h>
        #include <inttypes.h>
        #include <limits.h>
        #include <stdint.h>
        #include <stdio.h>
        #include <stdlib.h>
        #include <string.h>

        _Static_assert(sizeof(float) == 4, "tcs2c requires IEEE-754 binary32");
        _Static_assert(FLT_RADIX == 2 && FLT_MANT_DIG == 24,
            "tcs2c requires IEEE-754 binary32");
        #if FLT_EVAL_METHOD != 0
        #error "tcs2c strict mode requires FLT_EVAL_METHOD == 0"
        #endif

        typedef void (*TcsTrace)(void *);

        typedef struct TcsObjectHeader { uint32_t type_id; } TcsObjectHeader;
        #define TCS_STRING UINT32_C(0xfffffff1)
        #define TCS_BOX_I32 UINT32_C(0xfffffff2)
        #define TCS_BOX_F32 UINT32_C(0xfffffff3)
        #define TCS_BOX_BOOL UINT32_C(0xfffffff4)

        typedef struct TcsString {
            uint32_t type_id;
            size_t length;
            unsigned char data[];
        } TcsString;

        typedef struct TcsArray {
            uint32_t type_id;
            size_t length;
            size_t element_size;
            TcsTrace trace_element;
            void *data;
        } TcsArray;

        typedef struct TcsList {
            uint32_t type_id;
            size_t length;
            size_t capacity;
            size_t element_size;
            TcsTrace trace_element;
            void *data;
        } TcsList;

        static uint32_t tcs_digest;

        /* closure: fnptr + 捕捉変数 cell の配列。capture は変数単位
           (il-spec §7) — 捕捉される local は heap cell へ box される */
        typedef struct TcsClosure {
            uint32_t type_id;
            void *fn;
            size_t count;
            void *cells[];
        } TcsClosure;

        /* Dictionary: chained hash。key は i32 か string、value は 8 byte
           slot に value_size 分を格納する。反復順は Lua と一致しない
           (どちらも順序未規定)。 */
        typedef struct TcsDictNode {
            struct TcsDictNode *next;
            int32_t key_i;
            TcsString *key_s;
            unsigned char value[8];
        } TcsDictNode;

        #define TCS_DICT_BUCKETS 64
        typedef struct TcsDict {
            uint32_t type_id;
            TcsDictNode *buckets[TCS_DICT_BUCKETS];
            int32_t count;
            int32_t key_is_string;
            size_t value_size;
            TcsTrace trace_value;
        } TcsDict;

        /* dict 節は後方定義を参照するため前方宣言 */
        static void *tcs_alloc(size_t size);
        static void *tcs_alloc_traced(size_t size, TcsTrace trace);
        static void *tcs_realloc(void *old, size_t size);
        static void tcs_trace_array(void *object);
        static void tcs_trace_list(void *object);
        static void tcs_trace_dict(void *object);
        static void *tcs_nonnull(void *object);
        static _Noreturn void tcs_fault(const char *kind);
        static bool tcs_string_equal(TcsString *left, TcsString *right);

        static TcsDict *
        tcs_dict_new(uint32_t type_id, int32_t key_is_string, size_t value_size, TcsTrace trace)
        {
            TcsDict *dict = tcs_alloc_traced(sizeof(*dict), tcs_trace_dict);
            dict->type_id = type_id;
            dict->trace_value = trace;
            dict->key_is_string = key_is_string;
            dict->value_size = value_size;
            return dict;
        }

        static uint32_t
        tcs_dict_hash(TcsDict *dict, int32_t key_i, TcsString *key_s)
        {
            uint32_t h = 2166136261u;
            if (dict->key_is_string) {
                for (size_t i = 0; i < key_s->length; i++)
                    h = (h ^ (unsigned char)key_s->data[i]) * 16777619u;
            } else {
                for (int i = 0; i < 4; i++)
                    h = (h ^ (((uint32_t)key_i >> (8 * i)) & 0xFF)) * 16777619u;
            }
            return h;
        }

        static TcsDictNode *
        tcs_dict_find(TcsDict *dict, int32_t key_i, TcsString *key_s)
        {
            tcs_nonnull(dict);
            if (dict->key_is_string) tcs_nonnull(key_s);
            uint32_t bucket = tcs_dict_hash(dict, key_i, key_s)
                % TCS_DICT_BUCKETS;
            for (TcsDictNode *node = dict->buckets[bucket]; node != NULL;
                 node = node->next) {
                if (dict->key_is_string
                        ? tcs_string_equal(node->key_s, key_s)
                        : node->key_i == key_i)
                    return node;
            }
            return NULL;
        }

        static void *
        tcs_dict_put(TcsDict *dict, int32_t key_i, TcsString *key_s)
        {
            TcsDictNode *node = tcs_dict_find(dict, key_i, key_s);
            if (node != NULL) return node->value;
            uint32_t bucket = tcs_dict_hash(dict, key_i, key_s)
                % TCS_DICT_BUCKETS;
            node = tcs_alloc(sizeof(*node));
            node->key_i = key_i;
            node->key_s = key_s;
            node->next = dict->buckets[bucket];
            dict->buckets[bucket] = node;
            dict->count++;
            return node->value;
        }

        static void *
        tcs_dict_at(TcsDict *dict, int32_t key_i, TcsString *key_s)
        {
            TcsDictNode *node = tcs_dict_find(dict, key_i, key_s);
            if (node == NULL) tcs_fault("key-not-found");
            return node->value;
        }

        static bool
        tcs_dict_contains(TcsDict *dict, int32_t key_i, TcsString *key_s)
        {
            return tcs_dict_find(dict, key_i, key_s) != NULL;
        }

        static bool
        tcs_dict_tryget(TcsDict *dict, int32_t key_i, TcsString *key_s,
            void *out_value, const void *fallback)
        {
            TcsDictNode *node = tcs_dict_find(dict, key_i, key_s);
            memcpy(out_value, node != NULL ? node->value : fallback,
                dict->value_size);
            return node != NULL;
        }

        static bool
        tcs_dict_remove(TcsDict *dict, int32_t key_i, TcsString *key_s)
        {
            tcs_nonnull(dict);
            if (dict->key_is_string) tcs_nonnull(key_s);
            uint32_t bucket = tcs_dict_hash(dict, key_i, key_s)
                % TCS_DICT_BUCKETS;
            for (TcsDictNode **link = &dict->buckets[bucket]; *link != NULL;
                 link = &(*link)->next) {
                TcsDictNode *node = *link;
                if (dict->key_is_string
                        ? tcs_string_equal(node->key_s, key_s)
                        : node->key_i == key_i) {
                    *link = node->next;
                    dict->count--;
                    return true;
                }
            }
            return false;
        }

        static int32_t
        tcs_dict_count(TcsDict *dict)
        {
            tcs_nonnull(dict);
            return dict->count;
        }

        static int
        tcs_type_in_range(uint32_t type_id, uint32_t first, uint32_t last)
        {
            return type_id >= first && type_id <= last;
        }

        static _Noreturn void
        tcs_fault(const char *kind)
        {
            fprintf(stderr, "TinyC# fault: %s\n", kind);
            exit(EXIT_FAILURE);
        }

        static void *
        tcs_nonnull(void *object)
        {
            if (object == NULL) tcs_fault("null");
            return object;
        }

        static TcsString *
        tcs_string_new(const unsigned char *data, size_t length)
        {
            TcsString *string;
            if (length > SIZE_MAX - sizeof(*string))
                tcs_fault("allocation-overflow");
            string = tcs_alloc(sizeof(*string) + length);
            string->type_id = TCS_STRING;
            string->length = length;
            if (length != 0 && data != NULL) memcpy(string->data, data, length);
            return string;
        }

        static TcsString *
        tcs_string_concat(TcsString *left, TcsString *right)
        {
            TcsString *result;
            tcs_nonnull(left);
            tcs_nonnull(right);
            if (right->length > SIZE_MAX - left->length)
                tcs_fault("string-length-overflow");
            result = tcs_string_new(NULL, left->length + right->length);
            if (left->length != 0)
                memcpy(result->data, left->data, left->length);
            if (right->length != 0)
                memcpy(result->data + left->length, right->data, right->length);
            return result;
        }

        static bool
        tcs_string_equal(TcsString *left, TcsString *right)
        {
            if (left == NULL || right == NULL) return left == right;
            return left->length == right->length
                && (left->length == 0
                    || memcmp(left->data, right->data, left->length) == 0);
        }

        static int32_t
        tcs_string_length(TcsString *string)
        {
            tcs_nonnull(string);
            if (string->length > INT32_MAX) tcs_fault("string-length-overflow");
            return (int32_t)string->length;
        }

        static uint32_t
        tcs_f32_bits(float value)
        {
            uint32_t bits;
            memcpy(&bits, &value, sizeof(bits));
            return bits;
        }

        static size_t
        tcs_normalize_exponent(char buffer[64])
        {
            char *exponent = strchr(buffer, 'e');
            char *read;
            char *write;
            if (exponent == NULL) exponent = strchr(buffer, 'E');
            if (exponent == NULL) return strlen(buffer);
            read = exponent + 1;
            write = exponent + 1;
            if (*read == '+') read++;
            else if (*read == '-') *write++ = *read++;
            while (*read == '0' && read[1] != '\0') read++;
            memmove(write, read, strlen(read) + 1);
            return strlen(buffer);
        }

        static size_t
        tcs_format_f32(float value, char buffer[64])
        {
            int precision;
            int written = -1;
            for (precision = 1; precision <= 9; precision++) {
                char *end;
                float parsed;
                written = snprintf(buffer, 64, "%.*g", precision, (double)value);
                if (written < 0 || written >= 64) tcs_fault("float-format");
                written = (int)tcs_normalize_exponent(buffer);
                parsed = strtof(buffer, &end);
                if (*end == '\0' && tcs_f32_bits(parsed) == tcs_f32_bits(value))
                    return (size_t)written;
            }
            written = snprintf(buffer, 64, "%.9g", (double)value);
            if (written < 0 || written >= 64) tcs_fault("float-format");
            return tcs_normalize_exponent(buffer);
        }

        static TcsString *
        tcs_string_i32(int32_t value)
        {
            char buffer[32];
            int written = snprintf(buffer, sizeof(buffer), "%" PRId32, value);
            if (written < 0 || (size_t)written >= sizeof(buffer))
                tcs_fault("integer-format");
            return tcs_string_new((const unsigned char *)buffer, (size_t)written);
        }

        static TcsString *
        tcs_string_f32(float value)
        {
            char buffer[64];
            size_t length = tcs_format_f32(value, buffer);
            return tcs_string_new((const unsigned char *)buffer, length);
        }

        static TcsString *
        tcs_string_bool(bool value)
        {
            static const unsigned char true_text[] = "true";
            static const unsigned char false_text[] = "false";
            return value
                ? tcs_string_new(true_text, 4)
                : tcs_string_new(false_text, 5);
        }

        static TcsString *
        tcs_string_tostring(TcsString *value)
        {
            static const unsigned char nil_text[] = "nil";
            return value == NULL ? tcs_string_new(nil_text, 3) : value;
        }

        static void
        tcs_print_newline(void)
        {
            fputc('\n', stdout);
        }

        static void
        tcs_print_i32(int32_t value)
        {
            printf("%" PRId32 "\n", value);
        }

        static void
        tcs_print_f32(float value)
        {
            char buffer[64];
            size_t length = tcs_format_f32(value, buffer);
            fwrite(buffer, 1, length, stdout);
            fputc('\n', stdout);
        }

        static void
        tcs_print_bool(bool value)
        {
            fputs(value ? "true\n" : "false\n", stdout);
        }

        static void
        tcs_print_string(TcsString *value)
        {
            if (value == NULL) {
                fputs("nil\n", stdout);
                return;
            }
            if (value->length != 0) fwrite(value->data, 1, value->length, stdout);
            fputc('\n', stdout);
        }

        static TcsArray *
        tcs_array_new(uint32_t type_id, int32_t length, size_t element_size, TcsTrace trace)
        {
            TcsArray *array;
            if (length < 0) tcs_fault("negative-array-length");
            if ((size_t)length > SIZE_MAX / element_size)
                tcs_fault("allocation-overflow");
            array = tcs_alloc_traced(sizeof(*array), tcs_trace_array);
            array->type_id = type_id;
            array->trace_element = trace;
            array->length = (size_t)length;
            array->element_size = element_size;
            if (length != 0) array->data = tcs_alloc((size_t)length * element_size);
            return array;
        }

        static void *
        tcs_array_at(TcsArray *array, int32_t index)
        {
            tcs_nonnull(array);
            if (index < 0 || (size_t)index >= array->length)
                tcs_fault("bounds");
            return (unsigned char *)array->data + (size_t)index * array->element_size;
        }

        static int32_t
        tcs_array_length(TcsArray *array)
        {
            tcs_nonnull(array);
            if (array->length > INT32_MAX) tcs_fault("array-length-overflow");
            return (int32_t)array->length;
        }

        static TcsList *
        tcs_list_new(uint32_t type_id, size_t element_size, TcsTrace trace)
        {
            TcsList *list = tcs_alloc_traced(sizeof(*list), tcs_trace_list);
            list->type_id = type_id;
            list->trace_element = trace;
            list->element_size = element_size;
            return list;
        }

        static void
        tcs_list_add(TcsList *list, const void *value, size_t element_size)
        {
            size_t capacity;
            tcs_nonnull(list);
            if (list->element_size == 0) list->element_size = element_size;
            if (list->element_size != element_size) tcs_fault("list-element-type");
            if (list->length >= INT32_MAX) tcs_fault("list-length-overflow");
            if (list->length == list->capacity) {
                capacity = list->capacity == 0 ? 4 : list->capacity * 2;
                if (capacity < list->capacity
                    || capacity > SIZE_MAX / list->element_size)
                    tcs_fault("allocation-overflow");
                list->data = tcs_realloc(list->data,
                    capacity * list->element_size);
                list->capacity = capacity;
            }
            memcpy((unsigned char *)list->data
                + list->length * list->element_size, value, list->element_size);
            list->length++;
        }

        static void *
        tcs_list_at(TcsList *list, int32_t index)
        {
            tcs_nonnull(list);
            if (index < 0 || (size_t)index >= list->length)
                tcs_fault("bounds");
            return (unsigned char *)list->data + (size_t)index * list->element_size;
        }

        static int32_t
        tcs_list_length(TcsList *list)
        {
            tcs_nonnull(list);
            return (int32_t)list->length;
        }

        static float
        tcs_f32(uint32_t bits)
        {
            float value;
            memcpy(&value, &bits, sizeof(value));
            return value;
        }

        static int32_t
        tcs_idiv(int32_t left, int32_t right)
        {
            if (right == 0) tcs_fault("divide-by-zero");
            if (left == INT32_MIN && right == -1) tcs_fault("divide-overflow");
            return left / right;
        }

        static int32_t
        tcs_irem(int32_t left, int32_t right)
        {
            if (right == 0) tcs_fault("divide-by-zero");
            if (left == INT32_MIN && right == -1) tcs_fault("divide-overflow");
            return left % right;
        }

        static int32_t
        tcs_shl(int32_t value, int32_t count)
        {
            return (int32_t)((uint32_t)value << ((uint32_t)count & UINT32_C(31)));
        }

        static int32_t
        tcs_shr(int32_t value, int32_t count)
        {
            uint32_t shift = (uint32_t)count & UINT32_C(31);
            uint32_t bits = (uint32_t)value;
            if (shift == 0) return value;
            if (value >= 0) return (int32_t)(bits >> shift);
            return (int32_t)((bits >> shift) | (~UINT32_C(0) << (32 - shift)));
        }

        static void
        tcs_digest_float(float value)
        {
            uint32_t bits = tcs_f32_bits(value);
            unsigned int shift;
            for (shift = 0; shift < 32; shift += 8) {
                tcs_digest ^= (bits >> shift) & UINT32_C(0xff);
                tcs_digest *= UINT32_C(16777619);
            }
        }

        """;
}
