namespace TinyCs.Tcs2c;

internal sealed partial class CEmitter
{
    private const string RuntimePrelude = """
        /* Generated by tcs2c from TinyC# IL. */
        /* strict f32 flags: -ffp-contract=off -fexcess-precision=standard */
        #include <stdalign.h>
        #include <stdbool.h>
        #include <stddef.h>
        #include <errno.h>
        #include <math.h>
        #include <float.h>
        #include <inttypes.h>
        #include <limits.h>
        #include <stdint.h>
        #include <stdio.h>
        #include <stdlib.h>
        #include <string.h>
        #include <time.h>

        _Static_assert(sizeof(float) == 4, "tcs2c requires IEEE-754 binary32");
        _Static_assert(FLT_RADIX == 2 && FLT_MANT_DIG == 24,
            "tcs2c requires IEEE-754 binary32");
        #if FLT_EVAL_METHOD != 0
        #error "tcs2c strict mode requires FLT_EVAL_METHOD == 0"
        #endif
        /* runtime prelude は使われない helper を含む */
        #pragma GCC diagnostic ignored "-Wunused-function"

        /* ---- heap object の共通形。全 heap object は TcsGcHeader の直後に
           payload を置く (GC は CRuntime.Gc 節)。文字列 literal は static
           object (TCS_GC_STATIC) で、heap list には載らない ---- */
        typedef struct TcsLayout {
            uint32_t size;            /* 値 1 個の byte 数 */
            uint32_t count;           /* pointer slot 数 */
            const uint32_t *offsets;  /* 各 pointer slot の byte offset */
        } TcsLayout;

        enum {
            TCS_KIND_RAW = 0,     /* pointer を含まない (string / buffer) */
            TCS_KIND_OBJECT,      /* layout 1 個分の値 (class instance / cell) */
            TCS_KIND_ARRAY,       /* TcsArray + inline 要素 (layout = 要素) */
            TCS_KIND_LIST,        /* TcsList (layout = 要素) */
            TCS_KIND_DICT,        /* TcsDict (layout = 値) */
            TCS_KIND_DICT_NODE,   /* TcsDictNode (layout = 値) */
            TCS_KIND_CLOSURE      /* TcsClosure (cells は OBJECT) */
        };
        /* flags: MARK = 旧世代 mark-sweep の生存印、STATIC = 静的 object
           (literal)、OLD = 旧世代 (malloc 個別)、DIRTY = remembered set 登録済み、
           FORWARD = 昇格済みの若い object (next が昇格先) */
        enum { TCS_GC_MARK = 1u, TCS_GC_STATIC = 2u, TCS_GC_OLD = 4u,
               TCS_GC_DIRTY = 8u, TCS_GC_FORWARD = 16u };

        typedef struct TcsGcHeader {
            _Alignas(max_align_t) struct TcsGcHeader *next;
            const TcsLayout *layout;
            size_t size;              /* payload bytes */
            uint32_t kind;
            uint32_t flags;
        } TcsGcHeader;
        #define TCS_GC_PAYLOAD(hdr) \
            ((void *)((unsigned char *)(hdr) + sizeof(TcsGcHeader)))
        #define TCS_GC_HEADER(ptr) \
            ((TcsGcHeader *)((unsigned char *)(ptr) - sizeof(TcsGcHeader)))

        typedef struct TcsString {
            size_t length;
            unsigned char data[];
        } TcsString;

        typedef struct TcsArray {
            size_t length;
            size_t element_size;
            _Alignas(max_align_t) unsigned char data[];
        } TcsArray;

        typedef struct TcsList {
            size_t length;
            size_t capacity;
            size_t element_size;
            void *data;               /* RAW heap buffer (要素は list が trace) */
        } TcsList;

        static uint32_t tcs_digest;

        /* Nullable<T> (il-spec §13): has = 値あり */
        typedef struct TcsOptI32 { bool has; int32_t v; } TcsOptI32;
        typedef struct TcsOptF32 { bool has; float v; } TcsOptF32;
        typedef struct TcsOptBool { bool has; bool v; } TcsOptBool;

        /* closure: fnptr + 捕捉変数 cell の配列。capture は変数単位
           (il-spec §7) — 捕捉される local は heap cell へ box される */
        typedef struct TcsClosure {
            void *fn;
            void *cells[];
        } TcsClosure;

        /* Dictionary: chained hash (bucket 数は count に応じて倍化)。key は
           i32 か string、value は node 末尾の value_size byte (struct 値可)。
           反復順は Lua と一致しない (どちらも順序未規定)。 */
        typedef struct TcsDictNode {
            struct TcsDictNode *next;
            int32_t key_i;
            TcsString *key_s;
            _Alignas(max_align_t) unsigned char value[];
        } TcsDictNode;

        typedef struct TcsDict {
            struct TcsDictNode **buckets;   /* RAW heap buffer */
            size_t bucket_count;
            int32_t count;
            int32_t key_is_string;
            size_t value_size;
        } TcsDict;

        static _Noreturn void tcs_fault(const char *kind);
        static void *tcs_nonnull(void *object);
        static bool tcs_string_equal(TcsString *left, TcsString *right);
        static void *tcs_gc_alloc(uint32_t kind, const TcsLayout *layout,
            size_t size);
        static void *tcs_alloc(size_t size);   /* RAW (pointer なし) */
        static void tcs_gc_mark_statics(void);     /* 生成側で定義 (旧世代 root) */
        static void tcs_gc_forward_statics(void);  /* 生成側で定義 (境界の昇格) */
        static void tcs_wb(const void *owner);     /* ライトバリア */
        static void *tcs_gc_promote(void *pointer);
        static void tcs_gc_forward_value(void *value, const TcsLayout *layout);

        static int
        tcs_type_in_range(uint32_t type_id, uint32_t first, uint32_t last)
        {
            return type_id >= first && type_id <= last;
        }

        typedef struct TcsObjectHeaderView { uint32_t type_id; } TcsObjectHeaderView;

        /* 明示 downcast: null はそのまま、型が合わなければ fault */
        static void *
        tcs_cast(void *object, uint32_t first, uint32_t last)
        {
            if (object != NULL
                && !tcs_type_in_range(((TcsObjectHeaderView *)object)->type_id, first, last))
                tcs_fault("invalid-cast");
            return object;
        }

        static _Noreturn void
        tcs_fault(const char *kind)
        {
            fprintf(stderr, "TinyC# fault: %s\n", kind);
            exit(EXIT_FAILURE);
        }

        static void *
        tcs_nonnull(void *object)
        {
            if (object == NULL) tcs_fault("null");
            return object;
        }

        static TcsString *
        tcs_string_new(const unsigned char *data, size_t length)
        {
            TcsString *string;
            if (length > SIZE_MAX - sizeof(*string))
                tcs_fault("allocation-overflow");
            string = tcs_alloc(sizeof(*string) + length);
            string->length = length;
            if (length != 0 && data != NULL) memcpy(string->data, data, length);
            return string;
        }

        static TcsString *
        tcs_string_concat(TcsString *left, TcsString *right)
        {
            TcsString *result;
            tcs_nonnull(left);
            tcs_nonnull(right);
            if (right->length > SIZE_MAX - left->length)
                tcs_fault("string-length-overflow");
            result = tcs_string_new(NULL, left->length + right->length);
            if (left->length != 0)
                memcpy(result->data, left->data, left->length);
            if (right->length != 0)
                memcpy(result->data + left->length, right->data, right->length);
            return result;
        }

        static bool
        tcs_string_equal(TcsString *left, TcsString *right)
        {
            if (left == NULL || right == NULL) return left == right;
            return left->length == right->length
                && (left->length == 0
                    || memcmp(left->data, right->data, left->length) == 0);
        }

        static int32_t
        tcs_string_length(TcsString *string)
        {
            tcs_nonnull(string);
            if (string->length > INT32_MAX) tcs_fault("string-length-overflow");
            return (int32_t)string->length;
        }

        static uint32_t
        tcs_f32_bits(float value)
        {
            uint32_t bits;
            memcpy(&bits, &value, sizeof(bits));
            return bits;
        }

        static size_t
        tcs_format_f32(float value, char buffer[64])
        {
            /* Lua backend の __tcs_fstr と同じ %.6g → %.8g → %.9g の順で
               round-trip する最短を選ぶ (il-spec §13。桁数の刻みまで揃えないと
               100.0f が "1e+02" / "100" に割れる) */
            static const int ladder[3] = { 6, 8, 9 };
            int step;
            int written = -1;
            for (step = 0; step < 3; step++) {
                int precision = ladder[step];
                char *end;
                float parsed;
                written = snprintf(buffer, 64, "%.*g", precision, (double)value);
                if (written < 0 || written >= 64) tcs_fault("float-format");
                parsed = strtof(buffer, &end);
                if (*end == '\0' && tcs_f32_bits(parsed) == tcs_f32_bits(value))
                    return (size_t)written;
            }
            written = snprintf(buffer, 64, "%.9g", (double)value);
            if (written < 0 || written >= 64) tcs_fault("float-format");
            return (size_t)written;
        }

        static TcsString *
        tcs_string_i32(int32_t value)
        {
            char buffer[32];
            int written = snprintf(buffer, sizeof(buffer), "%" PRId32, value);
            if (written < 0 || (size_t)written >= sizeof(buffer))
                tcs_fault("integer-format");
            return tcs_string_new((const unsigned char *)buffer, (size_t)written);
        }

        static TcsString *
        tcs_string_f32(float value)
        {
            char buffer[64];
            size_t length = tcs_format_f32(value, buffer);
            return tcs_string_new((const unsigned char *)buffer, length);
        }

        static TcsString *
        tcs_string_bool(bool value)
        {
            static const unsigned char true_text[] = "true";
            static const unsigned char false_text[] = "false";
            return value
                ? tcs_string_new(true_text, 4)
                : tcs_string_new(false_text, 5);
        }

        static TcsString *
        tcs_string_tostring(TcsString *value)
        {
            static const unsigned char nil_text[] = "nil";
            return value == NULL ? tcs_string_new(nil_text, 3) : value;
        }

        static void
        tcs_print_newline(void)
        {
            fputc('\n', stdout);
        }

        static void
        tcs_print_i32(int32_t value)
        {
            printf("%" PRId32 "\n", value);
        }

        static void
        tcs_print_f32(float value)
        {
            char buffer[64];
            size_t length = tcs_format_f32(value, buffer);
            fwrite(buffer, 1, length, stdout);
            fputc('\n', stdout);
        }

        static void
        tcs_print_bool(bool value)
        {
            fputs(value ? "true\n" : "false\n", stdout);
        }

        static void
        tcs_print_string(TcsString *value)
        {
            if (value == NULL) {
                fputs("nil\n", stdout);
                return;
            }
            if (value->length != 0) fwrite(value->data, 1, value->length, stdout);
            fputc('\n', stdout);
        }

        static float
        tcs_f32(uint32_t bits)
        {
            float value;
            memcpy(&value, &bits, sizeof(value));
            return value;
        }

        static int32_t
        tcs_idiv(int32_t left, int32_t right)
        {
            if (right == 0) tcs_fault("divide-by-zero");
            if (left == INT32_MIN && right == -1) tcs_fault("divide-overflow");
            return left / right;
        }

        static int32_t
        tcs_irem(int32_t left, int32_t right)
        {
            if (right == 0) tcs_fault("divide-by-zero");
            if (left == INT32_MIN && right == -1) tcs_fault("divide-overflow");
            return left % right;
        }

        static int32_t
        tcs_shl(int32_t value, int32_t count)
        {
            return (int32_t)((uint32_t)value << ((uint32_t)count & UINT32_C(31)));
        }

        static int32_t
        tcs_shr(int32_t value, int32_t count)
        {
            uint32_t shift = (uint32_t)count & UINT32_C(31);
            uint32_t bits = (uint32_t)value;
            if (shift == 0) return value;
            if (value >= 0) return (int32_t)(bits >> shift);
            return (int32_t)((bits >> shift) | (~UINT32_C(0) << (32 - shift)));
        }

        static void
        tcs_digest_float(float value)
        {
            uint32_t bits = tcs_f32_bits(value);
            unsigned int shift;
            for (shift = 0; shift < 32; shift += 8) {
                tcs_digest ^= (bits >> shift) & UINT32_C(0xff);
                tcs_digest *= UINT32_C(16777619);
            }
        }

        """;
}
