-- Generated by TinyC# transpiler
Game = {}
Game.__index = Game

function Game.new()
  local self = setmetatable({}, Game)
  return self
end

function Game.Update(frame)
  return "[frame " .. tostring(frame) .. "] Hello from TinyC#!"
end
