using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TinyCs;

public partial class LuaEmitter
{
    private readonly StringBuilder _sb = new();
    private int _indent;
    private bool _headerEmitted;

    public void Visit(CSharpCompilation compilation, SemanticModel model, SyntaxTree tree)
    {
        if (!_headerEmitted)
        {
            _sb.AppendLine("-- Generated by TinyC# transpiler");
            _headerEmitted = true;
        }
        var root = tree.GetCompilationUnitRoot();
        foreach (var member in root.Members)
            VisitMember(model, member);
    }

    private void VisitMember(SemanticModel model, MemberDeclarationSyntax member)
    {
        switch (member)
        {
            case NamespaceDeclarationSyntax ns:
                foreach (var m in ns.Members) VisitMember(model, m);
                break;
            case FileScopedNamespaceDeclarationSyntax ns:
                foreach (var m in ns.Members) VisitMember(model, m);
                break;
            case ClassDeclarationSyntax cls:
                VisitClass(model, cls);
                break;
            case EnumDeclarationSyntax enumDecl:
                VisitEnum(model, enumDecl);
                break;
            case InterfaceDeclarationSyntax:
                // Interfaces are type-only; no Lua output
                break;
        }
    }

    private void VisitClass(SemanticModel model, ClassDeclarationSyntax cls)
    {
        var name = cls.Identifier.Text;

        var baseClass = cls.BaseList?.Types
            .Select(t => model.GetTypeInfo(t.Type).Type)
            .FirstOrDefault(t => t is { TypeKind: TypeKind.Class }
                and not { SpecialType: SpecialType.System_Object });

        AppendLine($"{name} = {{}}");
        AppendLine($"{name}.__index = {name}");
        if (baseClass != null)
            AppendLine($"setmetatable({name}, {{__index = {baseClass.Name}}})");
        AppendLine();

        var fieldInits = new List<(string Name, ExpressionSyntax? Init)>();
        ConstructorDeclarationSyntax? ctor = null;

        foreach (var member in cls.Members)
        {
            switch (member)
            {
                case FieldDeclarationSyntax field:
                    foreach (var v in field.Declaration.Variables)
                        fieldInits.Add((v.Identifier.Text, v.Initializer?.Value));
                    break;
                case PropertyDeclarationSyntax prop when IsAutoProperty(prop):
                    fieldInits.Add((prop.Identifier.Text, prop.Initializer?.Value));
                    break;
                case ConstructorDeclarationSyntax c:
                    ctor = c;
                    break;
            }
        }

        EmitConstructor(model, name, ctor, fieldInits);

        foreach (var member in cls.Members)
        {
            switch (member)
            {
                case MethodDeclarationSyntax method:
                    VisitMethod(model, name, method);
                    break;
                case PropertyDeclarationSyntax prop when !IsAutoProperty(prop)
                    && prop.AccessorList != null:
                    VisitCustomProperty(model, name, prop);
                    break;
            }
        }
    }

    private static bool IsAutoProperty(PropertyDeclarationSyntax prop) =>
        prop.AccessorList != null
        && prop.AccessorList.Accessors.All(a => a.Body == null && a.ExpressionBody == null);

    private void EmitConstructor(SemanticModel model, string className,
        ConstructorDeclarationSyntax? ctor, List<(string Name, ExpressionSyntax? Init)> fieldInits)
    {
        var ctorParams = ctor?.ParameterList.Parameters
            .Select(p => p.Identifier.Text).ToList() ?? [];

        AppendLine($"function {className}.new({string.Join(", ", ctorParams)})");
        _indent++;

        if (ctor?.Initializer != null)
        {
            var baseArgs = ctor.Initializer.ArgumentList.Arguments
                .Select(a => VisitExpression(model, a.Expression));
            var baseType = model.GetDeclaredSymbol(ctor)?.ContainingType?.BaseType;
            if (baseType != null && baseType.SpecialType != SpecialType.System_Object)
            {
                AppendLine($"local self = {baseType.Name}.new({string.Join(", ", baseArgs)})");
                AppendLine($"setmetatable(self, {className})");
            }
            else
            {
                AppendLine($"local self = setmetatable({{}}, {className})");
            }
        }
        else
        {
            AppendLine($"local self = setmetatable({{}}, {className})");
        }

        foreach (var (fieldName, init) in fieldInits)
        {
            if (init != null)
                AppendLine($"self.{fieldName} = {VisitExpression(model, init)}");
        }

        if (ctor?.Body != null)
        {
            foreach (var stmt in ctor.Body.Statements)
                VisitStatement(model, stmt);
        }
        else if (ctor?.ExpressionBody != null)
        {
            AppendLine(VisitExpression(model, ctor.ExpressionBody.Expression));
        }

        AppendLine("return self");
        _indent--;
        AppendLine("end");
        AppendLine();
    }

    private void VisitCustomProperty(SemanticModel model, string className,
        PropertyDeclarationSyntax prop)
    {
        var propName = prop.Identifier.Text;
        foreach (var accessor in prop.AccessorList!.Accessors)
        {
            var (prefix, extraParam) = accessor.IsKind(SyntaxKind.GetAccessorDeclaration)
                ? ("get_", "") : ("set_", "value");

            AppendLine($"function {className}:{prefix}{propName}({extraParam})");
            _indent++;
            if (accessor.Body != null)
                foreach (var s in accessor.Body.Statements) VisitStatement(model, s);
            else if (accessor.ExpressionBody != null)
            {
                var expr = VisitExpression(model, accessor.ExpressionBody.Expression);
                AppendLine(accessor.IsKind(SyntaxKind.GetAccessorDeclaration)
                    ? $"return {expr}" : expr);
            }
            _indent--;
            AppendLine("end");
            AppendLine();
        }
    }

    private void VisitEnum(SemanticModel model, EnumDeclarationSyntax enumDecl)
    {
        var name = enumDecl.Identifier.Text;
        AppendLine($"{name} = {{}}");
        int value = 0;
        foreach (var member in enumDecl.Members)
        {
            if (member.EqualsValue != null)
            {
                var constVal = model.GetConstantValue(member.EqualsValue.Value);
                if (constVal.HasValue && constVal.Value is int v)
                    value = v;
            }
            AppendLine($"{name}.{member.Identifier.Text} = {value}");
            value++;
        }
        AppendLine();
    }

    private void VisitMethod(SemanticModel model, string className,
        MethodDeclarationSyntax method)
    {
        var methodName = method.Identifier.Text;
        var isStatic = method.Modifiers.Any(SyntaxKind.StaticKeyword);
        var paramNames = method.ParameterList.Parameters
            .Select(p => p.Identifier.Text).ToList();
        var sep = isStatic ? "." : ":";

        AppendLine($"function {className}{sep}{methodName}({string.Join(", ", paramNames)})");
        _indent++;

        if (method.Body != null)
            foreach (var stmt in method.Body.Statements)
                VisitStatement(model, stmt);
        else if (method.ExpressionBody != null)
            AppendLine($"return {VisitExpression(model, method.ExpressionBody.Expression)}");

        _indent--;
        AppendLine("end");
        AppendLine();
    }

    // Output helpers
    private void AppendLine(string line = "")
    {
        if (string.IsNullOrEmpty(line))
            _sb.AppendLine();
        else
            _sb.AppendLine($"{new string(' ', _indent * 2)}{line}");
    }

    public override string ToString() => _sb.ToString().TrimEnd() + "\n";
}
