using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TinyCs;

public class LuaEmitter
{
    private readonly StringBuilder _sb = new();
    private int _indent;

    public void Visit(CSharpCompilation compilation, SemanticModel model, SyntaxTree tree)
    {
        _sb.AppendLine("-- Generated by TinyC# transpiler");
        var root = tree.GetCompilationUnitRoot();
        foreach (var member in root.Members)
        {
            VisitMember(model, member);
        }
    }

    private void VisitMember(SemanticModel model, MemberDeclarationSyntax member)
    {
        switch (member)
        {
            case NamespaceDeclarationSyntax ns:
                foreach (var m in ns.Members) VisitMember(model, m);
                break;
            case FileScopedNamespaceDeclarationSyntax ns:
                foreach (var m in ns.Members) VisitMember(model, m);
                break;
            case ClassDeclarationSyntax cls:
                VisitClass(model, cls);
                break;
        }
    }

    private void VisitClass(SemanticModel model, ClassDeclarationSyntax cls)
    {
        var name = cls.Identifier.Text;
        AppendLine($"local {name} = {{}}");
        AppendLine($"{name}.__index = {name}");
        AppendLine();

        foreach (var member in cls.Members)
        {
            switch (member)
            {
                case MethodDeclarationSyntax method:
                    VisitMethod(model, name, method);
                    break;
            }
        }
    }

    private void VisitMethod(SemanticModel model, string className, MethodDeclarationSyntax method)
    {
        var methodName = method.Identifier.Text;
        var isStatic = method.Modifiers.Any(SyntaxKind.StaticKeyword);
        var parameters = method.ParameterList.Parameters;

        var paramNames = new List<string>();
        if (!isStatic) paramNames.Add("self");
        foreach (var p in parameters) paramNames.Add(p.Identifier.Text);

        var sep = isStatic ? "." : ":";
        AppendLine($"function {className}{sep}{methodName}({string.Join(", ", isStatic ? paramNames : paramNames.Skip(1))})");
        _indent++;

        if (method.Body != null)
        {
            foreach (var stmt in method.Body.Statements)
            {
                VisitStatement(model, stmt);
            }
        }
        else if (method.ExpressionBody != null)
        {
            AppendLine($"return {VisitExpression(model, method.ExpressionBody.Expression)}");
        }

        _indent--;
        AppendLine("end");
        AppendLine();
    }

    private void VisitStatement(SemanticModel model, StatementSyntax stmt)
    {
        switch (stmt)
        {
            case ReturnStatementSyntax ret:
                if (ret.Expression != null)
                    AppendLine($"return {VisitExpression(model, ret.Expression)}");
                else
                    AppendLine("return");
                break;
            case LocalDeclarationStatementSyntax local:
                foreach (var v in local.Declaration.Variables)
                {
                    var init = v.Initializer != null ? $" = {VisitExpression(model, v.Initializer.Value)}" : "";
                    AppendLine($"local {v.Identifier.Text}{init}");
                }
                break;
            case ExpressionStatementSyntax exprStmt:
                AppendLine(VisitExpression(model, exprStmt.Expression));
                break;
            case IfStatementSyntax ifStmt:
                VisitIf(model, ifStmt);
                break;
            case WhileStatementSyntax whileStmt:
                AppendLine($"while {VisitExpression(model, whileStmt.Condition)} do");
                _indent++;
                VisitStatement(model, whileStmt.Statement);
                _indent--;
                AppendLine("end");
                break;
            case BlockSyntax block:
                foreach (var s in block.Statements)
                    VisitStatement(model, s);
                break;
            case BreakStatementSyntax:
                AppendLine("break");
                break;
        }
    }

    private void VisitIf(SemanticModel model, IfStatementSyntax ifStmt)
    {
        AppendLine($"if {VisitExpression(model, ifStmt.Condition)} then");
        _indent++;
        VisitStatement(model, ifStmt.Statement);
        _indent--;

        if (ifStmt.Else != null)
        {
            if (ifStmt.Else.Statement is IfStatementSyntax elseIf)
            {
                Append("elseif ");
                VisitElseIf(model, elseIf);
            }
            else
            {
                AppendLine("else");
                _indent++;
                VisitStatement(model, ifStmt.Else.Statement);
                _indent--;
                AppendLine("end");
            }
        }
        else
        {
            AppendLine("end");
        }
    }

    private void VisitElseIf(SemanticModel model, IfStatementSyntax ifStmt)
    {
        _sb.AppendLine($"{VisitExpression(model, ifStmt.Condition)} then");
        _indent++;
        VisitStatement(model, ifStmt.Statement);
        _indent--;

        if (ifStmt.Else != null)
        {
            if (ifStmt.Else.Statement is IfStatementSyntax elseIf)
            {
                Append("elseif ");
                VisitElseIf(model, elseIf);
            }
            else
            {
                AppendLine("else");
                _indent++;
                VisitStatement(model, ifStmt.Else.Statement);
                _indent--;
                AppendLine("end");
            }
        }
        else
        {
            AppendLine("end");
        }
    }

    private string VisitExpression(SemanticModel model, ExpressionSyntax expr)
    {
        return expr switch
        {
            LiteralExpressionSyntax lit => VisitLiteral(lit),
            IdentifierNameSyntax id => id.Identifier.Text,
            BinaryExpressionSyntax bin => VisitBinary(model, bin),
            PrefixUnaryExpressionSyntax prefix => VisitPrefixUnary(model, prefix),
            ParenthesizedExpressionSyntax paren => $"({VisitExpression(model, paren.Expression)})",
            InvocationExpressionSyntax invocation => VisitInvocation(model, invocation),
            MemberAccessExpressionSyntax memberAccess => VisitMemberAccess(model, memberAccess),
            AssignmentExpressionSyntax assignment => VisitAssignment(model, assignment),
            _ => $"--[[ TODO: {expr.Kind()} ]]"
        };
    }

    private string VisitLiteral(LiteralExpressionSyntax lit)
    {
        return lit.Kind() switch
        {
            SyntaxKind.NumericLiteralExpression => lit.Token.Text,
            SyntaxKind.StringLiteralExpression => lit.Token.Text,
            SyntaxKind.TrueLiteralExpression => "true",
            SyntaxKind.FalseLiteralExpression => "false",
            SyntaxKind.NullLiteralExpression => "nil",
            _ => $"--[[ TODO literal: {lit.Kind()} ]]"
        };
    }

    private string VisitBinary(SemanticModel model, BinaryExpressionSyntax bin)
    {
        var left = VisitExpression(model, bin.Left);
        var right = VisitExpression(model, bin.Right);
        var op = bin.Kind() switch
        {
            SyntaxKind.AddExpression => "+",
            SyntaxKind.SubtractExpression => "-",
            SyntaxKind.MultiplyExpression => "*",
            SyntaxKind.DivideExpression => "/",
            SyntaxKind.ModuloExpression => "%",
            SyntaxKind.EqualsExpression => "==",
            SyntaxKind.NotEqualsExpression => "~=",
            SyntaxKind.LessThanExpression => "<",
            SyntaxKind.LessThanOrEqualExpression => "<=",
            SyntaxKind.GreaterThanExpression => ">",
            SyntaxKind.GreaterThanOrEqualExpression => ">=",
            SyntaxKind.LogicalAndExpression => "and",
            SyntaxKind.LogicalOrExpression => "or",
            _ => $"--[[{bin.Kind()}]]"
        };
        return $"{left} {op} {right}";
    }

    private string VisitPrefixUnary(SemanticModel model, PrefixUnaryExpressionSyntax prefix)
    {
        var operand = VisitExpression(model, prefix.Operand);
        return prefix.Kind() switch
        {
            SyntaxKind.UnaryMinusExpression => $"-{operand}",
            SyntaxKind.LogicalNotExpression => $"not {operand}",
            _ => $"--[[ TODO unary: {prefix.Kind()} ]]"
        };
    }

    private string VisitInvocation(SemanticModel model, InvocationExpressionSyntax invocation)
    {
        var args = string.Join(", ", invocation.ArgumentList.Arguments.Select(a => VisitExpression(model, a.Expression)));
        var target = VisitExpression(model, invocation.Expression);
        return $"{target}({args})";
    }

    private string VisitMemberAccess(SemanticModel model, MemberAccessExpressionSyntax memberAccess)
    {
        var obj = VisitExpression(model, memberAccess.Expression);
        var member = memberAccess.Name.Identifier.Text;
        return $"{obj}.{member}";
    }

    private string VisitAssignment(SemanticModel model, AssignmentExpressionSyntax assignment)
    {
        var left = VisitExpression(model, assignment.Left);
        var right = VisitExpression(model, assignment.Right);
        return assignment.Kind() switch
        {
            SyntaxKind.SimpleAssignmentExpression => $"{left} = {right}",
            SyntaxKind.AddAssignmentExpression => $"{left} = {left} + {right}",
            SyntaxKind.SubtractAssignmentExpression => $"{left} = {left} - {right}",
            SyntaxKind.MultiplyAssignmentExpression => $"{left} = {left} * {right}",
            SyntaxKind.DivideAssignmentExpression => $"{left} = {left} / {right}",
            _ => $"--[[ TODO assign: {assignment.Kind()} ]]"
        };
    }

    private void AppendLine(string line = "")
    {
        if (string.IsNullOrEmpty(line))
            _sb.AppendLine();
        else
            _sb.AppendLine($"{new string(' ', _indent * 2)}{line}");
    }

    private void Append(string text)
    {
        _sb.Append($"{new string(' ', _indent * 2)}{text}");
    }

    public override string ToString() => _sb.ToString().TrimEnd() + "\n";
}
