using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TinyCs;

public partial class LuaEmitter
{
    private readonly StringBuilder _sb = new();
    private int _indent;
    private bool _headerEmitted;
    private int _luaLine = 1;
    private (string File, int Line)? _currentSource;
    private int _continueCounter;
    private readonly Stack<int> _continueStack = new();
    public List<string> Warnings { get; } = [];
    public SourceMap SourceMap { get; } = new();
    // Types declared in these trees are type-check only (--ref); they have no
    // Lua definition, so `new` on them must produce a plain table.
    public HashSet<SyntaxTree> ReferenceTrees { get; } = [];

    private bool IsReferenceOnlyType(ITypeSymbol? type) =>
        type != null && type.DeclaringSyntaxReferences
            .Any(r => ReferenceTrees.Contains(r.SyntaxTree));

    public void Visit(CSharpCompilation compilation, SemanticModel model,
        SyntaxTree tree, bool emitNonGlobalMembers = true,
        bool emitGlobalStatements = true)
    {
        if (!_headerEmitted)
        {
            AppendLine("-- Generated by TinyC# transpiler");
            _headerEmitted = true;
        }
        var root = tree.GetCompilationUnitRoot();
        if (emitNonGlobalMembers)
        {
            foreach (var member in root.Members)
            {
                if (member is not GlobalStatementSyntax)
                    VisitMember(model, member);
            }
        }

        if (emitGlobalStatements)
        {
            foreach (var global in root.Members.OfType<GlobalStatementSyntax>())
                VisitGlobalStatement(model, global);
        }
    }

    private void VisitMember(SemanticModel model, MemberDeclarationSyntax member)
    {
        if (TinyCsComplianceFacts.TryGetUnsupportedSyntax(member, out _))
        {
            WarnUnsupportedMember(member);
            return;
        }

        switch (member)
        {
            case NamespaceDeclarationSyntax ns:
                foreach (var m in ns.Members) VisitMember(model, m);
                break;
            case FileScopedNamespaceDeclarationSyntax ns:
                foreach (var m in ns.Members) VisitMember(model, m);
                break;
            case ClassDeclarationSyntax cls:
                VisitClass(model, cls);
                break;
            case RecordDeclarationSyntax rec:
                VisitRecord(model, rec);
                break;
            case EnumDeclarationSyntax enumDecl:
                VisitEnum(model, enumDecl);
                break;
            case InterfaceDeclarationSyntax:
                // Interfaces are type-only; no Lua output
                break;
            case GlobalStatementSyntax global:
                VisitGlobalStatement(model, global);
                break;
            default:
                WarnUnsupportedMember(member);
                break;
        }
    }

    private void VisitGlobalStatement(SemanticModel model,
        GlobalStatementSyntax global) =>
        VisitStatement(model, global.Statement);

    private void VisitClass(SemanticModel model, ClassDeclarationSyntax cls)
    {
        SetSource(cls);
        var name = cls.Identifier.Text;

        var baseClass = cls.BaseList?.Types
            .Select(t => model.GetTypeInfo(t.Type).Type)
            .FirstOrDefault(t => t is { TypeKind: TypeKind.Class }
                and not { SpecialType: SpecialType.System_Object });

        AppendLine($"{name} = {{}}");
        AppendLine($"{name}.__index = {name}");
        if (baseClass != null)
            AppendLine($"setmetatable({name}, {{__index = {baseClass.Name}}})");
        AppendLine();

        var fieldInits = new List<(string Name, ExpressionSyntax? Init, ITypeSymbol? Type)>();
        var staticFieldInits = new List<(string Name, ExpressionSyntax? Init, ITypeSymbol? Type)>();
        ConstructorDeclarationSyntax? ctor = null;

        foreach (var member in cls.Members)
        {
            switch (member)
            {
                case FieldDeclarationSyntax field:
                    var isStatic = field.Modifiers.Any(SyntaxKind.StaticKeyword)
                        || field.Modifiers.Any(SyntaxKind.ConstKeyword);
                    var typeInfo = model.GetTypeInfo(field.Declaration.Type);
                    foreach (var v in field.Declaration.Variables)
                    {
                        if (isStatic)
                        {
                            staticFieldInits.Add((v.Identifier.Text, v.Initializer?.Value,
                                typeInfo.Type));
                        }
                        else
                            fieldInits.Add((v.Identifier.Text, v.Initializer?.Value,
                                typeInfo.Type));
                    }
                    break;
                case PropertyDeclarationSyntax prop when IsAutoProperty(prop):
                    fieldInits.Add((prop.Identifier.Text, prop.Initializer?.Value,
                        model.GetTypeInfo(prop.Type).Type));
                    break;
                case ConstructorDeclarationSyntax c:
                    ctor = c;
                    break;
            }
        }

        // Emit static fields on the class table
        foreach (var (fieldName, init, type) in staticFieldInits)
        {
            if (init != null)
                AppendLine($"{name}.{fieldName} = {VisitExpression(model, init)}");
            else
                AppendLine($"{name}.{fieldName} = {GetDefaultValueForType(type!)}");
        }
        if (staticFieldInits.Count > 0) AppendLine();

        EmitConstructor(model, name, ctor, fieldInits);

        foreach (var member in cls.Members)
        {
            switch (member)
            {
                case MethodDeclarationSyntax method:
                    VisitMethod(model, name, method);
                    break;
                case PropertyDeclarationSyntax prop when !IsAutoProperty(prop)
                    && prop.AccessorList != null:
                    VisitCustomProperty(model, name, prop);
                    break;
                case FieldDeclarationSyntax:
                case PropertyDeclarationSyntax prop when IsAutoProperty(prop):
                case ConstructorDeclarationSyntax:
                    break;
                default:
                    WarnUnsupportedMember(member);
                    break;
            }
        }
    }

    private static bool IsAutoProperty(PropertyDeclarationSyntax prop) =>
        prop.AccessorList != null
        && prop.AccessorList.Accessors.All(a => a.Body == null && a.ExpressionBody == null);

    private void EmitConstructor(SemanticModel model, string className,
        ConstructorDeclarationSyntax? ctor,
        List<(string Name, ExpressionSyntax? Init, ITypeSymbol? Type)> fieldInits)
    {
        var ctorParams = ctor?.ParameterList.Parameters
            .Select(p => p.Identifier.Text).ToList() ?? [];

        AppendLine($"function {className}.new({string.Join(", ", ctorParams)})");
        _indent++;

        if (ctor?.Initializer != null)
        {
            var baseArgs = ctor.Initializer.ArgumentList.Arguments
                .Select(a => VisitExpression(model, a.Expression));
            var baseType = model.GetDeclaredSymbol(ctor)?.ContainingType?.BaseType;
            if (baseType != null && baseType.SpecialType != SpecialType.System_Object)
            {
                AppendLine($"local self = {baseType.Name}.new({string.Join(", ", baseArgs)})");
                AppendLine($"setmetatable(self, {className})");
            }
            else
            {
                AppendLine($"local self = setmetatable({{}}, {className})");
            }
        }
        else
        {
            AppendLine($"local self = setmetatable({{}}, {className})");
        }

        foreach (var (fieldName, init, type) in fieldInits)
        {
            if (init != null)
                AppendLine($"self.{fieldName} = {VisitExpression(model, init)}");
            else
                AppendLine($"self.{fieldName} = {GetDefaultValueForType(type!)}");
        }

        if (ctor?.Body != null)
        {
            foreach (var stmt in ctor.Body.Statements)
                VisitStatement(model, stmt);
        }
        else if (ctor?.ExpressionBody != null)
        {
            AppendLine(VisitExpression(model, ctor.ExpressionBody.Expression));
        }

        AppendLine("return self");
        _indent--;
        AppendLine("end");
        AppendLine();
    }

    private void VisitCustomProperty(SemanticModel model, string className,
        PropertyDeclarationSyntax prop)
    {
        var propName = prop.Identifier.Text;
        foreach (var accessor in prop.AccessorList!.Accessors)
        {
            var (prefix, extraParam) = accessor.IsKind(SyntaxKind.GetAccessorDeclaration)
                ? ("get_", "") : ("set_", "value");

            AppendLine($"function {className}:{prefix}{propName}({extraParam})");
            _indent++;
            if (accessor.Body != null)
                foreach (var s in accessor.Body.Statements) VisitStatement(model, s);
            else if (accessor.ExpressionBody != null)
            {
                var expr = VisitExpression(model, accessor.ExpressionBody.Expression);
                AppendLine(accessor.IsKind(SyntaxKind.GetAccessorDeclaration)
                    ? $"return {expr}" : expr);
            }
            _indent--;
            AppendLine("end");
            AppendLine();
        }
    }

    private void VisitRecord(SemanticModel model, RecordDeclarationSyntax rec)
    {
        SetSource(rec);
        var name = rec.Identifier.Text;

        AppendLine($"{name} = {{}}");
        AppendLine($"{name}.__index = {name}");
        AppendLine();

        // Positional record: parameter list → constructor + properties
        var paramNames = rec.ParameterList?.Parameters
            .Select(p => p.Identifier.Text).ToList() ?? [];

        AppendLine($"function {name}.new({string.Join(", ", paramNames)})");
        _indent++;
        AppendLine($"local self = setmetatable({{}}, {name})");
        foreach (var param in paramNames)
            AppendLine($"self.{param} = {param}");
        AppendLine("return self");
        _indent--;
        AppendLine("end");
        AppendLine();

        // __eq: value-based equality for record types
        if (paramNames.Count > 0)
        {
            var eqParts = paramNames.Select(p => $"a.{p} == b.{p}");
            AppendLine($"function {name}.__eq(a, b)");
            _indent++;
            AppendLine($"return {string.Join(" and ", eqParts)}");
            _indent--;
            AppendLine("end");
            AppendLine();
        }

        // Emit any explicitly defined methods
        foreach (var member in rec.Members)
        {
            if (member is MethodDeclarationSyntax method)
                VisitMethod(model, name, method);
            else
                WarnUnsupportedMember(member);
        }
    }

    private void VisitEnum(SemanticModel model, EnumDeclarationSyntax enumDecl)
    {
        SetSource(enumDecl);
        var name = enumDecl.Identifier.Text;
        AppendLine($"{name} = {{}}");
        int value = 0;
        foreach (var member in enumDecl.Members)
        {
            if (member.EqualsValue != null)
            {
                var constVal = model.GetConstantValue(member.EqualsValue.Value);
                if (constVal.HasValue && constVal.Value is int v)
                    value = v;
            }
            AppendLine($"{name}.{member.Identifier.Text} = {value}");
            value++;
        }
        AppendLine();
    }

    private void VisitMethod(SemanticModel model, string className,
        MethodDeclarationSyntax method)
    {
        SetSource(method);
        var methodName = method.Identifier.Text;
        var isStatic = method.Modifiers.Any(SyntaxKind.StaticKeyword);
        var paramNames = method.ParameterList.Parameters
            .Select(p => p.Identifier.Text).ToList();
        var sep = isStatic ? "." : ":";

        AppendLine($"function {className}{sep}{methodName}({string.Join(", ", paramNames)})");
        _indent++;

        if (method.Body != null)
            foreach (var stmt in method.Body.Statements)
                VisitStatement(model, stmt);
        else if (method.ExpressionBody != null)
            AppendLine($"return {VisitExpression(model, method.ExpressionBody.Expression)}");

        _indent--;
        AppendLine("end");
        AppendLine();
    }

    private void SetSource(SyntaxNode node)
    {
        var loc = node.GetLocation().GetLineSpan();
        var file = loc.Path ?? "<source>";
        _currentSource = (file, loc.StartLinePosition.Line + 1);
    }

    private void ClearSource() => _currentSource = null;

    // Output helpers
    private void AppendLine(string line = "")
    {
        if (string.IsNullOrEmpty(line))
        {
            _sb.AppendLine();
            _luaLine++;
        }
        else
        {
            if (_currentSource.HasValue)
            {
                SourceMap.Add(_luaLine, _currentSource.Value.File, _currentSource.Value.Line);
                _currentSource = null;
            }
            var output = $"{new string(' ', _indent * 2)}{line}";
            _sb.AppendLine(output);
            _luaLine += CountOutputLines(output);
        }
    }

    private static int CountOutputLines(string output) =>
        output.Count(ch => ch == '\n') + 1;

    private string WarnUnsupported(SyntaxNode node, string description)
    {
        if (TinyCsComplianceFacts.TryGetUnsupportedSyntax(node,
            out var syntaxName))
        {
            description = syntaxName;
            return $"--[[ unsupported: {description} ]]";
        }

        Warnings.Add(TinyCsComplianceFacts.FormatWarning(node,
            TinyCsDiagnosticIds.UnsupportedSyntax,
            $"unsupported syntax: {description}"));
        return $"--[[ unsupported: {description} ]]";
    }

    private void WarnUnsupportedMember(MemberDeclarationSyntax member) =>
        _ = WarnUnsupported(member, $"member: {member.Kind()}");

    public override string ToString() => _sb.ToString().TrimEnd() + "\n";
}
