using Microsoft.CodeAnalysis;

namespace TinyCs;

// chunk prelude: 言語 lowering 用の chunk-local helper (整数除算、trunc、
// Nullable、型判定、float 文字列化、`new T[n]`、hot reload registry)。
// module mode の define chunk は同名 global (_G 経由、runtime の TinySystem.*)
// へ fallback する (ModuleArtifacts の alias 一覧と対応)。
public partial class LuaEmitter
{
    private void EmitChunkPrelude()
    {
        AppendLine("-- Generated by TinyC# transpiler");
        // C# の整数除算/剰余 (0 方向 truncation) は Lua の // と % (floor
        // 由来) と負数で結果がずれるため、言語 lowering 用 helper を
        // chunk-local で常時定義する (--no-runtime でも動く言語機能)。
        // module mode の define chunk は同名 global (_G 経由、runtime の
        // TinySystem.idiv/irem) へ fallback する。
        AppendLine("local function __tcs_idiv(a, b)");
        AppendLine("  local q = a // b");
        AppendLine("  if a % b ~= 0 and (a < 0) ~= (b < 0) then q = q + 1 end");
        AppendLine("  return q");
        AppendLine("end");
        AppendLine("local function __tcs_irem(a, b)");
        AppendLine("  return a - __tcs_idiv(a, b) * b");
        AppendLine("end");
        // C# の (int)f は 0 方向 truncation で整数になる。Lua の float を
        // そのまま流すと 2.7 のまま残る (添字・%d・整数演算で乖離) ため、
        // float→int cast は常にこの helper を通す (C backend も同じ契約)
        AppendLine("local function __tcs_trunc(x)");
        AppendLine("  local i = math.tointeger(x)");
        AppendLine("  if i then return i end");
        AppendLine("  if x >= 0 then return math.floor(x) end");
        AppendLine("  return math.ceil(x)");
        AppendLine("end");
        // C# のシフト: count は 31 でマスク、int の >> は算術 (符号拡張)。
        // Lua native は count 無マスク・>> 論理なので helper を通す
        AppendLine("local function __tcs_shl(a, n) return a << (n & 31) end");
        AppendLine("local function __tcs_shr(a, n)");
        AppendLine("  n = n & 31");
        AppendLine("  if a >= 0 then return a >> n end");
        AppendLine("  return ~((~a) >> n)");
        AppendLine("end");
        // Nullable<T> (il-spec §13): nil = 値なし。.Value の値なしは fault、
        // lifted 演算は片方でも nil なら nil (比較は false)、bool? の & |
        // は三値論理。op 関数は定数なので closure 確保は無い
        AppendLine("local function __tcs_nval(v)");
        AppendLine("  if v == nil then error(\"Nullable object must have a value\") end");
        AppendLine("  return v");
        AppendLine("end");
        AppendLine("local function __tcs_nget(v, d) if v == nil then return d end return v end");
        AppendLine("local function __tcs_nlift(a, b, f) if a == nil or b == nil then return nil end return f(a, b) end");
        AppendLine("local function __tcs_nlift1(a, f) if a == nil then return nil end return f(a) end");
        AppendLine("local function __tcs_ncmp(a, b, f) if a == nil or b == nil then return false end return f(a, b) end");
        AppendLine("local function __tcs_nand(a, b)");
        AppendLine("  if a == false or b == false then return false end");
        AppendLine("  if a == nil or b == nil then return nil end");
        AppendLine("  return true");
        AppendLine("end");
        AppendLine("local function __tcs_nor(a, b)");
        AppendLine("  if a == true or b == true then return true end");
        AppendLine("  if a == nil or b == nil then return nil end");
        AppendLine("  return false");
        AppendLine("end");
        AppendLine("local function __tcs_nnot(a) if a == nil then return nil end return not a end");
        AppendLine("local function __tcs_op_add(a, b) return a + b end");
        AppendLine("local function __tcs_op_sub(a, b) return a - b end");
        AppendLine("local function __tcs_op_mul(a, b) return a * b end");
        AppendLine("local function __tcs_op_div(a, b) return a / b end");
        AppendLine("local function __tcs_op_idiv(a, b) return __tcs_idiv(a, b) end");
        AppendLine("local function __tcs_op_irem(a, b) return __tcs_irem(a, b) end");
        AppendLine("local function __tcs_op_fmod(a, b) return math.fmod(a, b) end");
        AppendLine("local function __tcs_op_band(a, b) return a & b end");
        AppendLine("local function __tcs_op_bor(a, b) return a | b end");
        // bool? の ^ は boolean xor (a ~= b)
        AppendLine("local function __tcs_op_bxor(a, b) if type(a) == \"boolean\" then return a ~= b end return a ~ b end");
        AppendLine("local function __tcs_op_shl(a, b) return __tcs_shl(a, b) end");
        AppendLine("local function __tcs_op_shr(a, b) return __tcs_shr(a, b) end");
        AppendLine("local function __tcs_op_lt(a, b) return a < b end");
        AppendLine("local function __tcs_op_le(a, b) return a <= b end");
        AppendLine("local function __tcs_op_gt(a, b) return a > b end");
        AppendLine("local function __tcs_op_ge(a, b) return a >= b end");
        AppendLine("local function __tcs_op_neg(a) return -a end");
        AppendLine("local function __tcs_op_bnot(a) return ~a end");
        // C# の `is T` は「T またはその派生」(il-spec §9)。継承は
        // instance の metatable = class table、class table の
        // metatable.__index = base で表現しているため chain を辿る。
        AppendLine("local function __tcs_is(x, T)");
        AppendLine("  local mt = getmetatable(x)");
        AppendLine("  while mt do");
        AppendLine("    if mt == T then return true end");
        AppendLine("    local link = getmetatable(mt)");
        AppendLine("    mt = link and link.__index");
        AppendLine("  end");
        AppendLine("  return false");
        AppendLine("end");
        // f32 の shortest round-trip 10 進表記 (il-spec §13)。Lua 既定の
        // %.14g は余分な桁を出すため、%.6g/%.8g/%.9g の順で round-trip
        // する最短を選ぶ (binary32 は 9 桁で常に round-trip する)
        AppendLine("local function __tcs_fstr(v)");
        AppendLine("  if math.type(v) ~= \"float\" then return tostring(v) end");
        AppendLine("  local s = string.format(\"%.6g\", v)");
        AppendLine("  if tonumber(s) == v then return s end");
        AppendLine("  s = string.format(\"%.8g\", v)");
        AppendLine("  if tonumber(s) == v then return s end");
        AppendLine("  return string.format(\"%.9g\", v)");
        AppendLine("end");
        // `new T[n]` (値型 T): default を n 個詰めた sequence。init が
        // 関数 (struct の zero ctor) なら要素ごとに fresh な値
        AppendLine("local function __tcs_arr(n, init)");
        AppendLine("  local t = {}");
        AppendLine("  if type(init) == \"function\" then");
        AppendLine("    for i = 1, n do t[i] = init() end");
        AppendLine("  else");
        AppendLine("    for i = 1, n do t[i] = init end");
        AppendLine("  end");
        AppendLine("  return t");
        AppendLine("end");
        // T? の文字列化: null は C# と同じく空文字列
        AppendLine("local function __tcs_nstr(v)");
        AppendLine("  if v == nil then return \"\" end");
        AppendLine("  if math.type(v) == \"float\" then return __tcs_fstr(v) end");
        AppendLine("  return tostring(v)");
        AppendLine("end");
        // hot reload (il-design §6): 生存インスタンスの weak registry (opt-in)。
        // reload chunk と共有するため global。key = instance (weak)、
        // value = 構築時の class table (reload 後も identity 不変)
        if (InstanceRegistry)
            AppendLine("__tcs_instances = __tcs_instances or "
                + "setmetatable({}, { __mode = \"k\" })");
        _headerEmitted = true;
    }
}
