using System.Text;

namespace TinyCs;

public sealed record LuaRuntimeBundle(string Lua, int SourceMapLineOffset);

public static class LuaRuntime
{
    private const string RuntimeRelativePath = "runtime/tinysystem.lua";
    public const string RegistryRelativePath = "runtime/module_registry.lua";

    public static LuaRuntimeBundle EmbedRuntime(string lua)
    {
        var prelude = CreateEmbeddedPrelude(File.ReadAllText(FindRuntimePath()));
        return new LuaRuntimeBundle(prelude + lua, CountNewLines(prelude));
    }

    // repo 内の runtime lua を読む (native/test 用。wasm は埋め込み resource)。
    public static string LoadRuntimeFile(string relativePath) =>
        File.ReadAllText(FindPath(relativePath));

    public static string LoadTinySystemSource() =>
        File.ReadAllText(FindRuntimePath());

    public static string CreateEmbeddedPrelude(string runtimeSource)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by TinyC# transpiler");
        sb.AppendLine("-- TinyC# embedded runtime prelude");
        sb.AppendLine("do");
        sb.AppendLine("  local TinySystem = (function()");

        var normalizedRuntime = runtimeSource.Replace("\r\n", "\n").TrimEnd();
        foreach (var line in normalizedRuntime.Split('\n'))
            sb.AppendLine($"    {line}");

        sb.AppendLine("  end)()");
        sb.AppendLine("  _G.TinySystem = TinySystem");
        sb.AppendLine("  _G.List = TinySystem.List");
        sb.AppendLine("  _G.Dict = TinySystem.Dict");
        sb.AppendLine("  _G.Math = TinySystem.Math");
        sb.AppendLine("  _G.String = TinySystem.String");
        sb.AppendLine("  _G.Random = TinySystem.Random");
        sb.AppendLine("end");
        sb.AppendLine();
        return sb.ToString();
    }

    private static string FindRuntimePath() => FindPath(RuntimeRelativePath);

    private static string FindPath(string relativePath)
    {
        foreach (var start in new[]
        {
            AppContext.BaseDirectory,
            Environment.CurrentDirectory,
        })
        {
            var dir = start;
            while (!string.IsNullOrEmpty(dir))
            {
                var candidate = Path.Combine(dir, relativePath);
                if (File.Exists(candidate)) return candidate;

                var parent = Path.GetDirectoryName(dir);
                if (parent == dir) break;
                dir = parent;
            }
        }

        throw new FileNotFoundException(
            $"TinyC# runtime file not found: {relativePath}");
    }

    private static int CountNewLines(string text)
    {
        var count = 0;
        foreach (var ch in text)
        {
            if (ch == '\n') count++;
        }
        return count;
    }
}
