using System.Security.Cryptography;
using System.Text;

namespace TinyCs;

// doc/incremental-module-compilation-design.md §10-§11 の module artifact 層。
// LuaEmitter が記録した type 単位の section (宣言行 / static 初期化行) と
// ownership (定義 key 一覧) から、declare/define/initializers に分割した
// descriptor と、単一 entry Lua (bridge snapshot) を組み立てる。

// static field 1 本の metadata。Start/Length は module RawLua 内の
// 初期化行の範囲 (define chunk からは除外し、initializer thunk になる)。
public sealed record StaticFieldMeta(
    string Key, string DefaultLua, string InitHash, bool Pure,
    int Start, int Length);

// emitter が module 内で emit した runtime type 1 個の記録。
public sealed class EmittedTypeInfo
{
    public required string Name { get; init; }       // Lua global alias
    public required string Kind { get; init; }       // class | record | enum
    public string? BaseName { get; set; }
    // instance field/auto-property の形 (名前 + 初期化式)。変更は restart 境界。
    public string InstanceShape { get; set; } = "";
    // `Name = {}` 宣言行 (define chunk から除外し、registry の declare が担う)
    public List<(int Start, int Length)> DeclRanges { get; } = [];
    public List<StaticFieldMeta> StaticFields { get; set; } = [];
    // 定義が所有する type table の key (new / __index / method / accessor /
    // metamethod / enum member)。hot apply の削除 diff に使う。
    public List<string> DefinitionKeys { get; } = [];

    public EmittedTypeInfo Shifted(int spliceStart, int delta)
    {
        var copy = new EmittedTypeInfo
        {
            Name = Name,
            Kind = Kind,
            BaseName = BaseName,
            InstanceShape = InstanceShape,
            StaticFields = [.. StaticFields.Select(s =>
                s.Start > spliceStart ? s with { Start = s.Start + delta } : s)],
        };
        copy.DeclRanges.AddRange(DeclRanges.Select(r =>
            r.Start > spliceStart ? (r.Start + delta, r.Length) : r));
        copy.DefinitionKeys.AddRange(DefinitionKeys);
        return copy;
    }
}

public static class ModuleArtifactText
{
    public static string Sha256(string s) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(s)));

    // define chunk = module の RawLua から宣言行と static 初期化行を除いたもの。
    public static string BuildDefineLua(string rawLua,
        IEnumerable<EmittedTypeInfo> types)
    {
        var cuts = types
            .SelectMany(t => t.DeclRanges
                .Concat(t.StaticFields.Select(s => (s.Start, s.Length))))
            .OrderByDescending(c => c.Start);
        var sb = new StringBuilder(rawLua);
        foreach (var (start, length) in cuts)
            sb.Remove(start, length);
        return sb.ToString();
    }

    // type 1 個の static initializer chunk (emit 順の初期化行の連結)。
    public static string BuildTypeInitializerLua(string rawLua, EmittedTypeInfo type)
    {
        var sb = new StringBuilder();
        foreach (var s in type.StaticFields)
            sb.Append(rawLua, s.Start, s.Length);
        return sb.ToString();
    }

    public static string BuildFieldInitializerLua(string rawLua, StaticFieldMeta field)
        => rawLua.Substring(field.Start, field.Length);

    public static string EscapeLuaString(string s)
    {
        var sb = new StringBuilder("\"");
        foreach (var ch in s)
        {
            switch (ch)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                default: sb.Append(ch); break;
            }
        }
        return sb.Append('"').ToString();
    }
}

// bridge snapshot linker (§14.2)。全 active artifact から、空 registry からも
// 起動できる単一 entry Lua を deterministic に組み立てる。出力は
// idempotent bootstrap + registry:applyBatch + thin entry wrapper の return。
public static class ModuleLinker
{
    public static string LinkSnapshot(
        IReadOnlyList<SessionModuleArtifact> artifacts,
        int revision,
        string? entryClass,
        string tinySystemLua,
        string registryLua,
        bool emitAck = false)
    {
        var sb = new StringBuilder();
        sb.Append("-- Generated by TinyC# transpiler (module snapshot rev ")
          .Append(revision).Append(")\n");

        // idempotent bootstrap: 初回だけ TinySystem prelude と registry を作る。
        // reload では既存 identity を保つ (§14.2 bridge entry の実行契約)。
        sb.Append("local __rt = _G.__tcs_module_runtime\n");
        sb.Append("if not (__rt and __rt.abi == 1) then\n");
        sb.Append("  local TinySystem = (function()\n");
        AppendIndented(sb, tinySystemLua, "    ");
        sb.Append("  end)()\n");
        sb.Append("  _G.TinySystem = TinySystem\n");
        sb.Append("  _G.List = TinySystem.List\n");
        sb.Append("  _G.Dict = TinySystem.Dict\n");
        sb.Append("  _G.Math = TinySystem.Math\n");
        sb.Append("  _G.String = TinySystem.String\n");
        sb.Append("  _G.Random = TinySystem.Random\n");
        sb.Append("  _G.__tcs_idiv = TinySystem.idiv\n");
        sb.Append("  _G.__tcs_irem = TinySystem.irem\n");
        sb.Append("  _G.__tcs_is = TinySystem.instanceof\n");
        sb.Append("  local __registry_mod = (function()\n");
        AppendIndented(sb, registryLua, "    ");
        sb.Append("  end)()\n");
        sb.Append("  __rt = { abi = 1, registry = __registry_mod.new(_G) }\n");
        sb.Append("  _G.__tcs_module_runtime = __rt\n");
        sb.Append("end\n\n");

        sb.Append("local __result = __rt.registry:applyBatch({\n");
        sb.Append("  revision = ").Append(revision).Append(",\n");
        if (emitAck)
            sb.Append("  ack = true,\n");

        var entry = FindEntry(artifacts, entryClass);
        if (entry != null)
        {
            var (moduleId, type) = entry.Value;
            sb.Append("  entry = { type = ")
              .Append(ModuleArtifactText.EscapeLuaString(TypeId(moduleId, type.Name)))
              .Append(", keys = { ");
            foreach (var k in type.DefinitionKeys.Where(k => !k.StartsWith("__")))
                sb.Append(ModuleArtifactText.EscapeLuaString(k)).Append(", ");
            sb.Append("} },\n");
        }

        sb.Append("  modules = {\n");
        foreach (var a in artifacts)
            AppendModuleDescriptor(sb, a);
        sb.Append("  },\n");
        sb.Append("})\n");
        sb.Append("return __result.wrapper\n");
        return sb.ToString();
    }

    private static (string ModuleId, EmittedTypeInfo Type)? FindEntry(
        IReadOnlyList<SessionModuleArtifact> artifacts, string? entryClass)
    {
        if (entryClass == null)
            return null;
        foreach (var a in artifacts)
            foreach (var t in a.Types)
                if (t.Name == entryClass)
                    return (a.ModuleId, t);
        throw new InvalidOperationException($"entry class not found: {entryClass}");
    }

    internal static string TypeId(string moduleId, string typeName) =>
        moduleId + "#" + typeName;

    private static void AppendModuleDescriptor(StringBuilder sb,
        SessionModuleArtifact a)
    {
        var esc = ModuleArtifactText.EscapeLuaString;
        sb.Append("    {\n");
        sb.Append("      id = ").Append(esc(a.ModuleId)).Append(",\n");
        sb.Append("      hash = ").Append(esc(a.LuaHash)).Append(",\n");
        sb.Append("      types = {\n");
        foreach (var t in a.Types)
        {
            sb.Append("        { id = ").Append(esc(TypeId(a.ModuleId, t.Name)))
              .Append(", name = ").Append(esc(t.Name))
              .Append(", kind = ").Append(esc(t.Kind));
            if (t.BaseName != null)
                sb.Append(", base = ").Append(esc(t.BaseName));
            sb.Append(",\n          statics = { ");
            foreach (var s in t.StaticFields)
            {
                sb.Append("{ key = ").Append(esc(s.Key))
                  .Append(", default = ").Append(s.DefaultLua)
                  .Append(", pure = ").Append(s.Pure ? "true" : "false")
                  .Append(" }, ");
            }
            sb.Append("},\n          keys = { ");
            foreach (var k in t.DefinitionKeys)
                sb.Append(esc(k)).Append(", ");
            foreach (var s in t.StaticFields)
                sb.Append(esc(s.Key)).Append(", ");
            sb.Append("} },\n");
        }
        sb.Append("      },\n");

        // define/initializer は _ENV 引数付き function literal として埋め込む。
        // body 内の global 参照は registry の read-only module env に解決される。
        sb.Append("      define = function(_ENV)\n");
        sb.Append(ModuleArtifactText.BuildDefineLua(a.RawLua, a.Types));
        sb.Append("\n      end,\n");

        sb.Append("      inits = {\n");
        foreach (var t in a.Types.Where(t => t.StaticFields.Count > 0))
        {
            sb.Append("        [").Append(esc(TypeId(a.ModuleId, t.Name)))
              .Append("] = function(_ENV)\n");
            sb.Append(ModuleArtifactText.BuildTypeInitializerLua(a.RawLua, t));
            sb.Append("        end,\n");
        }
        sb.Append("      },\n");

        // 副作用なしと証明済みの static field だけ、hot apply の新規 field
        // 初期化用に field 単位 thunk を持つ (§11.3)。
        sb.Append("      initfns = {\n");
        foreach (var t in a.Types.Where(t => t.StaticFields.Any(s => s.Pure)))
        {
            sb.Append("        [").Append(esc(TypeId(a.ModuleId, t.Name)))
              .Append("] = {\n");
            foreach (var s in t.StaticFields.Where(s => s.Pure))
            {
                sb.Append("          [").Append(esc(s.Key))
                  .Append("] = function(_ENV)\n");
                sb.Append(ModuleArtifactText.BuildFieldInitializerLua(a.RawLua, s));
                sb.Append("          end,\n");
            }
            sb.Append("        },\n");
        }
        sb.Append("      },\n");
        sb.Append("    },\n");
    }

    private static void AppendIndented(StringBuilder sb, string source,
        string indent)
    {
        foreach (var line in source.Replace("\r\n", "\n").TrimEnd().Split('\n'))
        {
            if (line.Length == 0) sb.Append('\n');
            else sb.Append(indent).Append(line).Append('\n');
        }
    }
}
